server:
  port: 8080
  max-http-header-size: 16KB

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: email-service
          uri: ${EMAIL_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/emails/**
          filters:
            - StripPrefix=1
        - id: contact-service
          uri: ${CONTACT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/contacts/**
          filters:
            - StripPrefix=1
        - id: campaign-service
          uri: ${CAMPAIGN_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/campaigns/**
          filters:
            - StripPrefix=1
        - id: template-service
          uri: ${TEMPLATE_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/templates/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG