server:
  port: ${TEMPLATE_SERVICE_PORT:8085}
  max-http-header-size: 16KB
spring:
  application:
    name: template-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:correos_masivos_templates}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  data:
    redis:
      host: ${REDIS_HOST:correos-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-1zvh0tbtrif4683g.us.auth0.com/}
          audiences: ${AUTH0_AUDIENCE:XtrimIdentityAPI}

auth0:
  client-id: ${AUTH0_CLIENT_ID:f2dvMxIOFKGKUfFQMnpemQPeuJKsDaSh}
  client-secret: ${AUTH0_CLIENT_SECRET:Vd4QjYOBc4rn6pWMfmJHwdTqo1fsh8uefWXJsoJSGy9N98UeGiGav0Bu7emDLQbb}
  audience: ${AUTH0_AUDIENCE:XtrimIdentityAPI}
  domain: ${AUTH0_DOMAIN:https://dev-1zvh0tbtrif4683g.us.auth0.com}

logging:
  level:
    com.correos.masivos: ${LOG_LEVEL:INFO}
  file:
    path: ${LOG_FILE_PATH:./logs/}
    name: ${LOG_FILE_PATH:./logs/}template-service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always